export const actions = {
  profile: {
    DATA_FETCHING: "PROFILE_DATA_FETCHING",
    DATA_FETCHED: "PROFILE_DATA_FETCHED",
    DATA_FETCH_ERROR: "PROFILE_DATA_FETCH_ERROR",
    USER_DATA_EDITED: "PROFILE_USER_DATA_EDITED",
    IMAGE_UPDATED: "PROFILE_IMAGE_UPDATED",
  },
  posts: {
    DATA_FETCHING: "POSTS_DATA_FETCHING",
    DATA_FETCHED: "POSTS_DATA_FETCHED", // For initial fetch or full refresh
    DATA_APPEND: "POSTS_DATA_APPEND", // For appending new data on scroll
    DATA_FETCH_ERROR: "POSTS_DATA_FETCH_ERROR",
    INCREMENT_PAGE: "POSTS_INCREMENT_PAGE",
    NO_MORE_DATA: "POSTS_NO_MORE_DATA",
  },
};
